// reference

var province = $feature.province;

if (province == "Sankuru" || province == "Kasai" || province == "Kasai-Oriental" || province == "Kasaï" || province == "Kasaï-Oriental") {
    return "Crédits de la carte\n" +
    "Sources de données: GRID3 COD - Settlement Extents v3.1 (CIESIN 2024); GRID3 COD - Settlement Names v4.0 (unpublished); GRID3 COD - Health Areas v4.0 (unpublished); GRID3 COD - Health Facilities v4.0 (unpublished); GRID3 COD – Religious Centers v1.0 (MSPHP RDC et CIESIN 2024); GRID3 COD – Schools v1.0 (MSPHP RDC et CIESIN 2024); CIESIN COD Roads (unpublished).\n" +
    "Cette carte a été créée dans le cadre du projet de soutien à la mise en œuvre des activités du Projet de Vaccination des Enfants Zéro Dose du Fonds d'Accélération de l'Équité (FAE). Nous remercions le Programme Elargi de Vaccination (PEV) pour son soutien continu lors du processus de cartographie.\n\n" +
    "Conditions d'utilisation\n" +
    "Cette carte a été réalisée par CIESIN, Columbia University (2024) pour soutenir les activités de planification et de coordination liées à la fourniture des services de santé par le Ministère de la Santé Publique, Hygiène et Prévention (MSPHP) et le Programme Elargi de Vaccination (PEV). Cette carte est sous licence Creative Commons Attribution 4.0 International License, CC BY 4.0. Les utilisateurs sont libres d'utiliser, copier, distribuer, transmettre et adapter l'œuvre à des fins commerciales et non commerciales, sans restriction, à condition qu'une attribution claire de la source soit fournie.";
} else if (province == "Kasaï-Central" || province == "Kasai-Central") {
    return "Crédits de la carte\n" +
    "Sources de données: GRID3 COD - Settlement Extents v3.1 (CIESIN 2024); GRID3 COD - Settlement Names v3.0 (MSPHP RDC et CIESIN 2024); GRID3 COD - Health Areas v3.0 (MSPHP RDC et CIESIN 2024); GRID3 COD - Health Facilities v3.0 (MSPHP RDC et CIESIN 2024); GRID3 COD – Religious Centers, Schools and Points of Interest (POI) (unpublished); CIESIN COD Roads (unpublished).\n" +
    "Cette carte a été créée dans le cadre du projet cartographie digitale de la République Democratique du Congo (RDC) de la phase 2 GRID3 financé par la Fondation Bill et Melinda Gates (BMGF). Nous remercions l'École de Santé Publique de Kinshasa (ESPK) qui a effectué la collecte des données ainsi que le Programme Elargi de Vaccination (PEV) pour son soutien continu lors du processus de cartographie.\n\n" +
    "Conditions d'utilisation\n" +
    "Cette carte a été réalisée par CIESIN, Columbia University (2024) pour soutenir les activités de planification et de coordination liées à la fourniture des services de santé par le Ministère de la Santé Publique, Hygiène et Prévention (MSPHP) et le Programme Elargi de Vaccination (PEV). Cette carte est sous licence Creative Commons Attribution 4.0 International License, CC BY 4.0. Les utilisateurs sont libres d'utiliser, copier, distribuer, transmettre et adapter l'œuvre à des fins commerciales et non commerciales, sans restriction, à condition qu'une attribution claire de la source soit fournie.";
} else if (province == "Mongala" || province == "Tshopo") {
    return "Crédits de la carte\n" +
    "Sources de données: GRID3 COD - Settlement Extents v3.1 (CIESIN 2024); GRID3 COD - Settlement Names v4.0 (unpublished); GRID3 COD - Health Areas v4.0 (unpublished); GRID3 COD - Health Facilities v4.0 (unpublished); GRID3 COD – Religious Centers, Schools and Points of Interest (POI) (unpublished); CIESIN COD Roads (unpublished).\n" +
    "Cette carte a été créée dans le cadre du projet de soutien à la mise en œuvre des activités du Projet de Vaccination des Enfants Zéro Dose du Fonds d'Accélération de l'Équité (FAE). Nous remercions l'École de Santé Publique de Kinshasa (ESPK) qui a effectué la collecte des données ainsi que le Programme Elargi de Vaccination (PEV) pour son soutien continu lors du processus de cartographie.\n\n" +
    "Conditions d'utilisation\n" +
    "Cette carte a été réalisée par CIESIN, Columbia University (2024) pour soutenir les activités de planification et de coordination liées à la fourniture des services de santé par le Ministère de la Santé Publique, Hygiène et Prévention (MSPHP) et le Programme Elargi de Vaccination (PEV). Cette carte est sous licence Creative Commons Attribution 4.0 International License, CC BY 4.0. Les utilisateurs sont libres d'utiliser, copier, distribuer, transmettre et adapter l'œuvre à des fins commerciales et non commerciales, sans restriction, à condition qu'une attribution claire de la source soit fournie.";
} else if (province == "Haut-Katanga") {
    return "Crédits de la carte\n" +
    "Sources de données: GRID3 COD - Settlement Extents v3.1 (CIESIN 2024); GRID3 COD - Settlement Names v4.0 (unpublished); GRID3 COD - Health Areas v4.0 (unpublished); GRID3 COD - Health Facilities v4.0 (unpublished); GRID3 COD – Religious Centers v1.0 (MSPHP RDC et CIESIN 2024); GRID3 COD – Schools v1.0 (MSPHP RDC et CIESIN 2024); CIESIN COD Roads (unpublished).\n" +
    "Cette carte a été créée dans le cadre du projet de soutien à la mise en œuvre des activités du Projet de Vaccination des Enfants Zéro Dose du Fonds d'Accélération de l'Équité (FAE). Nous remercions le Programme Elargi de Vaccination (PEV) pour son soutien continu lors du processus de cartographie.\n\n" +
    "Conditions d'utilisation\n" +
    "Cette carte a été réalisée par CIESIN, Columbia University (2024) pour soutenir les activités de planification et de coordination liées à la fourniture des services de santé par le Ministère de la Santé Publique, Hygiène et Prévention (MSPHP) et le Programme Elargi de Vaccination (PEV). Cette carte est sous licence Creative Commons Attribution 4.0 International License, CC BY 4.0. Les utilisateurs sont libres d'utiliser, copier, distribuer, transmettre et adapter l'œuvre à des fins commerciales et non commerciales, sans restriction, à condition qu'une attribution claire de la source soit fournie.";
} else if (province == "Maniema") {
    return "Crédits de la carte\n" +
    "Sources de données: GRID3 COD - Settlement Extents v3.1 (CIESIN 2024); GRID3 COD - Settlement Names v3.0 (MSPHP RDC et CIESIN 2024); GRID3 COD - Health Areas v3.0 (MSPHP RDC et CIESIN 2024); GRID3 COD - Health Facilities v3.0 (MSPHP RDC et CIESIN 2024); GRID3 COD – Religious Centers, Schools and Points of Interest (POI) (unpublished); CIESIN COD Roads (unpublished).\n" +
    "Cette carte a été créée dans le cadre du projet de soutien à la mise en œuvre des activités du Projet de Vaccination des Enfants Zéro Dose du Fonds d'Accélération de l'Équité (FAE). Nous remercions l'École de Santé Publique de Kinshasa (ESPK) qui a effectué la collecte des données ainsi que le Programme Elargi de Vaccination (PEV) pour son soutien continu lors du processus de cartographie.\n\n" +
    "Conditions d'utilisation\n" +
    "Cette carte a été réalisée par CIESIN, Columbia University (2024) pour soutenir les activités de planification et de coordination liées à la fourniture des services de santé par le Ministère de la Santé Publique, Hygiène et Prévention (MSPHP) et le Programme Elargi de Vaccination (PEV). Cette carte est sous licence Creative Commons Attribution 4.0 International License, CC BY 4.0. Les utilisateurs sont libres d'utiliser, copier, distribuer, transmettre et adapter l'œuvre à des fins commerciales et non commerciales, sans restriction, à condition qu'une attribution claire de la source soit fournie.";
}